Db
EgorDikanskiy/Sparq pull request #5
Opened 2024-10-07 21:39 UTC by EgorDikanskiy

connect db

2024-10-12 21:27 UTC, koshakkkq requested changes

2024-10-12 21:27 UTC, koshakkkq commented on README.md
> +`fastapi dev main.py`
Лишнее

2024-10-12 21:27 UTC, koshakkkq commented on README.md
> +Чтобы подключиться к бд нужно указать её данные в файлах `alembic.ini` и `database.py`
Про миграции добавить надо. 
Конфиг для подключения надо задавать на уровене env переменных.

Можешь почитать про .env файл и переменные окружения. Сделай пример .env файла с нужными полями, и используей данные из .env для подключения к бд

https://habr.com/ru/articles/472674/

2024-10-12 21:27 UTC, koshakkkq commented on poetry.lock
> +name = "black"
Это форматер, лишнее, но сейчас ок.
Один пр = одно логическое изменение. Потом если нужно что-то откатить есть шанс откатить нужные изменения

2024-10-12 21:27 UTC, koshakkkq commented on pyproject.toml
> +line-length = 90
Давай побольше сделаем. 120 хотя бы. У меня это с запасом влезает в 16:9

2024-10-12 21:27 UTC, koshakkkq commented on requirements.txt
> -pytest==6.2.5
Сюда ничего добавлять не надо. Его надо выпилить отдельным PR

2024-10-12 21:27 UTC, koshakkkq commented on src/database.py
> +database_url = 'postgresql+asyncpg://username:password@localhost/dbname'
Конфигурационные переменные лучше унести в отдельную папку

2024-10-26 17:46 UTC, EgorDikanskiy commented on requirements.txt
> -pytest==6.2.5
на всякий оставлю, т.к c poetry проблемы

2024-10-26 17:46 UTC, EgorDikanskiy commented on README.md
> +Чтобы подключиться к бд нужно указать её данные в файлах `alembic.ini` и `database.py`
есть

2024-10-26 17:47 UTC, EgorDikanskiy commented on src/database.py
> +database_url = 'postgresql+asyncpg://username:password@localhost/dbname'
есть

2024-10-28 08:31 UTC, merged